#!/usr/bin/env python
from gimpfu import *
import csv

def selectionMargins(image):
    selection,x1,y1,x2,y2=pdb.gimp_selection_bounds(image)
    if not selection:
        pdb.gimp_message("No selection")
    else:
        gimp.message('L=%d\nU=%d\nR=%d\nD=%d' % (x1,y1,x2-x1,y2-y1))
        f = open("C:\\Users\\Elisar\\Desktop\\temp.csv", 'ab')
        writer = csv.writer(f)
        writer.writerow([x1,y2,x2-x1,y2-y1])
        f.close()

### Registration
desc='Show selection margins'
register(
    'selection-margins',desc,desc,'','','2019',desc,'*',
    [(PF_IMAGE, "image", "Input image", None),],[],
    selectionMargins,menu="<Image>/Select"
)

main()
